services:
  backend:
    build:
      context: backend/
      dockerfile: ./Dockerfile
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db


  frontend:
    build:
      context: frontend/
      dockerfile: ./Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend


  db:
    image: postgres:17-alpine
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
