services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      sh -c "./entrypoint.sh"
    depends_on:
      - db


  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:5173"
    depends_on:
      - backend


  db:
    image: postgres:17-alpine
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
