services:
  postgres:
    image: postgres
    container_name: db
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
      - environment:
          - POSTGRES_USER: ${DB_USER}
          - POSTGRES_PASSWORD: ${DB_PASS}
          - POSTGRES_DB: ${DB_NAME}
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gamers
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
