services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend
      - frontend
    networks:
      - app
  
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - app
    env_file:
      - .env
    depends_on:
      - db


  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    networks:
      - app
    depends_on:
      - backend


  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    networks:
      - app
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
  etc/letsencrypt:

networks:
  app:
