"""add yandex_id

Revision ID: 0843216cb684
Revises: 5e94d1e732a1
Create Date: 2025-05-10 20:43:14.203215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0843216cb684'
down_revision: Union[str, None] = '5e94d1e732a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('yandex_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['yandex_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'yandex_id')
    # ### end Alembic commands ###
