"""changed message user relationship + change message created_at to current_timestamp

Revision ID: 35bf13407521
Revises: 2ce431230e59
Create Date: 2025-04-19 19:33:48.410406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35bf13407521'
down_revision: Union[str, None] = '2ce431230e59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
