"""add delete cascade for user and other tables

Revision ID: 3c75b99b5431
Revises: ba5da8b7eb68
Create Date: 2025-04-24 19:12:20.772147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c75b99b5431'
down_revision: Union[str, None] = 'ba5da8b7eb68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
