"""add payment_id to user_sub

Revision ID: 54a9a6d58642
Revises: cb1d2a128747
Create Date: 2025-05-05 23:47:16.224567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54a9a6d58642'
down_revision: Union[str, None] = 'cb1d2a128747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('payment_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_subscriptions', 'payment_id')
    # ### end Alembic commands ###
