"""v6 add delete cascade for user and other tables

Revision ID: 5d725be18f89
Revises: c1ba3013b83f
Create Date: 2025-04-24 19:51:05.968075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d725be18f89'
down_revision: Union[str, None] = 'c1ba3013b83f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('teams_owner_id_fkey', 'teams', type_='foreignkey')
    op.create_foreign_key(None, 'teams', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.create_foreign_key('teams_owner_id_fkey', 'teams', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
