"""add delete cascade for user and other tables v4

Revision ID: 610d5f7c23b0
Revises: ba60834f485f
Create Date: 2025-04-24 19:42:38.891107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '610d5f7c23b0'
down_revision: Union[str, None] = 'ba60834f485f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
