"""change cascade teams chats

Revision ID: b4adbd9c7ca9
Revises: f293daffbdd4
Create Date: 2025-02-27 17:18:33.987893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4adbd9c7ca9'
down_revision: Union[str, None] = 'f293daffbdd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
