"""update cascade team_members and chats

Revision ID: cac74cd834be
Revises: 21e8c631f771
Create Date: 2025-02-27 19:03:52.946362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cac74cd834be'
down_revision: Union[str, None] = '21e8c631f771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chats_team_id_fkey', 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('team_members_user_id_fkey', 'team_members', type_='foreignkey')
    op.drop_constraint('team_members_team_id_fkey', 'team_members', type_='foreignkey')
    op.create_foreign_key(None, 'team_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'team_members', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.create_foreign_key('team_members_team_id_fkey', 'team_members', 'teams', ['team_id'], ['id'])
    op.create_foreign_key('team_members_user_id_fkey', 'team_members', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key('chats_team_id_fkey', 'chats', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###
