"""fix relationship teams chats

Revision ID: d2b2c40c311b
Revises: 1ed0279c5cbe
Create Date: 2025-02-25 15:19:31.659707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2b2c40c311b'
down_revision: Union[str, None] = '1ed0279c5cbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
