"""change cascade teams members chats

Revision ID: f293daffbdd4
Revises: d2d9d955cb68
Create Date: 2025-02-27 17:02:03.651914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f293daffbdd4'
down_revision: Union[str, None] = 'd2d9d955cb68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_members_chat_id_fkey', 'chat_members', type_='foreignkey')
    op.create_foreign_key(None, 'chat_members', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('messages_chat_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('teams_chat_id_fkey', 'teams', type_='foreignkey')
    op.create_foreign_key(None, 'teams', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.create_foreign_key('teams_chat_id_fkey', 'teams', 'chats', ['chat_id'], ['id'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_chat_id_fkey', 'messages', 'chats', ['chat_id'], ['id'])
    op.drop_constraint(None, 'chat_members', type_='foreignkey')
    op.create_foreign_key('chat_members_chat_id_fkey', 'chat_members', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###
