"""change cascade teams chats

Revision ID: f95abc6a3d37
Revises: b4adbd9c7ca9
Create Date: 2025-02-27 17:25:41.871931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f95abc6a3d37'
down_revision: Union[str, None] = 'b4adbd9c7ca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
