"""Добавил ondelete CASCADE в chat_members и chats

Revision ID: f95ea9802173
Revises: cac74cd834be
Create Date: 2025-02-27 19:05:49.767919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f95ea9802173'
down_revision: Union[str, None] = 'cac74cd834be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_members_chat_id_fkey', 'chat_members', type_='foreignkey')
    op.drop_constraint('chat_members_user_id_fkey', 'chat_members', type_='foreignkey')
    op.create_foreign_key(None, 'chat_members', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_members', type_='foreignkey')
    op.drop_constraint(None, 'chat_members', type_='foreignkey')
    op.create_foreign_key('chat_members_user_id_fkey', 'chat_members', 'users', ['user_id'], ['id'])
    op.create_foreign_key('chat_members_chat_id_fkey', 'chat_members', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###
